#pragma once

#include <cstddef>
#include <cstdint>
#include <vector>

#include "approach_map/map/types.hpp"

namespace approach_cost
{

/**
 * @brief Supported final-cost composition modes.
 */
enum class ModeId : uint8_t
{
  Mode1 = 1,
};

/**
 * @brief Inputs shared by all common cost computations.
 */
struct CommonCostInput
{
  approach_map::GridMeta meta;
  approach_map::XYPoint target_point_m;
  approach_map::XYPoint robot_point_m;
  std::vector<uint8_t> candidate_mask;
  std::vector<uint32_t> state_transition_counts;

  /// Unit direction of the object row (objects assumed laid out in a line).
  /// The preferred approach is perpendicular to this direction.
  bool has_object_row_dir{false};
  approach_map::XYPoint object_row_dir{0.0, 0.0};
};

/**
 * @brief Configuration for the common cost terms.
 */
struct CommonCostConfig
{
  double weight_target_distance{1.0};
  double weight_stability{1.0};
  double weight_approach_distance{1.0};
  double weight_approach_angle{1.0};
  std::size_t stability_window_radius_cells{1};
  float invalid_value{-1.0F};
};

/**
 * @brief Configuration for final cost composition.
 */
struct FinalCostConfig
{
  ModeId mode{ModeId::Mode1};
  CommonCostConfig common;
};

/**
 * @brief Output layers generated by cost_common.
 */
struct CommonCostLayers
{
  approach_map::GridDataF32 target_distance_cost;
  approach_map::GridDataF32 stability_cost;
  approach_map::GridDataF32 approach_distance_cost;
  approach_map::GridDataF32 approach_angle_cost;
  approach_map::GridDataF32 cost_common;
};

}  // namespace approach_cost
